# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MoJaB
tagline:             'محمد جواد بدیعی'
description:         'من مجابم.محمد جواد بدیعی.بچه مشدم.لپ‌تاپی دارم و سرسوزن شوقی.'
url:                 http://mojab.github.io
baseurl:             /blog/
paginate:            5

# About/contact
author:
  name:              Mohammad Jabad Badiei
  url:               https://twitter.com/_mojab_
  email:             m.j.badiee@gmail.com

# Custom vars
version:             1.0.1
